### ISSUE TITLE
Little problem about UVs

### ISSUE THREAD

**Issue by XanderXu** [maxxfrazer/RealityGeometries#3]
When I put  a image as texture, it's mirrored, the "b" becomes "d". It happens in Cone, Cylinder, Torus. But Cone and Cylinder bottom are right, and DetailPlane is right.

then I use `ModelDebugOptionsComponent(visualizationMode: .textureCoordinates)` to check uv, I find It's different to uv in Shaders. 

I think this is the problem: RealityKit mirror y-axis of uv in some step.
In Mesh of a Plane, the uv origin is at left-bottom corner, y-up to top. (use Shader to visualize uv)
When put image to a Plane, the uv origin is at left-top corner, y-up to bottom, just like UIKit. (use `ModelDebugOptionsComponent(visualizationMode: .textureCoordinates)` to visualize uv)

Maybe we should change uv in Mesh to match image. But I don't know is it the Right way ?

**Comment by maxxfrazer** [comment]
interesting. i don’t recall testing with any non-symmetrical images so can see how it was missed.
sounds like the fix would just be as simple as (1 - p.x) in the texture coordinate mapping. i’ll take a look at adding a fix over the weekend if i get chance, otherwise please feel free to open a PR if you can.

**Comment by maxxfrazer** [comment]
I've posted some updates to branch [`flip-uvs`](https://github.com/maxxfrazer/RealityGeometries/tree/flip-uvs). Looks better, but the cone UVs are a little off as mentioned in the commit.
